// Generated by scripts/gen-routes.mjs — edit the generator, not this file.
import { HomePage, homeMetadata } from '@/components/pages';

export const metadata = homeMetadata('ja');

export default function Page() {
  return <HomePage locale="ja" />;
}

