// Generated by scripts/gen-routes.mjs — edit the generator, not this file.
import type { ReactNode } from 'react';
import { SiteShell } from '@/components/pages';
import '../globals.css';

export default function Layout({ children }: { children: ReactNode }) {
  return <SiteShell locale="en">{children}</SiteShell>;
}

