// Generated by scripts/gen-routes.mjs — edit the generator, not this file.
import { PrivacyPage, privacyMetadata } from '@/components/pages';

export const metadata = privacyMetadata('en');

export default function Page() {
  return <PrivacyPage locale="en" />;
}

