// Generated by scripts/gen-routes.mjs — edit the generator, not this file.
import { TermsPage, termsMetadata } from '@/components/pages';

export const metadata = termsMetadata('en');

export default function Page() {
  return <TermsPage locale="en" />;
}

