// Generated by scripts/gen-routes.mjs — edit the generator, not this file.
import { PuzzlePage, puzzleMetadata } from '@/components/pages';

export const metadata = puzzleMetadata('zh', 'shogi');

export default function Page() {
  return <PuzzlePage locale="zh" slug="shogi" />;
}

