// Generated by scripts/gen-routes.mjs — edit the generator, not this file.
import { GamePage, gameMetadata } from '@/components/pages';

export const metadata = gameMetadata('ja', 'gomoku');

export default function Page() {
  return <GamePage locale="ja" slug="gomoku" />;
}

