/**
 * Generates the App Router files for every locale.
 *
 * English lives at the root; ko/ja/zh sit behind a path prefix. Each locale is
 * its own route group with its own root layout, which is what lets <html lang>
 * be statically correct per locale without a middleware rewrite.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const LOCALES = [
  { code: 'en', prefix: '' },
  { code: 'ko', prefix: 'ko' },
  { code: 'ja', prefix: 'ja' },
  { code: 'zh', prefix: 'zh' },
];

const GAME_SLUGS = ['gomoku', 'reversi', 'janggi', 'chess', 'shogi', 'go', 'baghchal', 'xiangqi', 'oware'];

/** Games with a puzzle set — see scripts/import-chess-puzzles.ts / scripts/gen-puzzles.ts. */
const PUZZLE_SLUGS = ['chess', 'janggi', 'shogi'];

const root = process.cwd();

function write(relPath, contents) {
  const full = join(root, relPath);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, `${contents.trimStart()}\n`, 'utf8');
  console.log('wrote', relPath);
}

const banner = '// Generated by scripts/gen-routes.mjs — edit the generator, not this file.';

for (const { code, prefix } of LOCALES) {
  const group = `app/(${code})`;
  const base = prefix ? `${group}/${prefix}` : group;

  write(
    `${group}/layout.tsx`,
    `
${banner}
import type { ReactNode } from 'react';
import { SiteShell } from '@/components/pages';
import '../globals.css';

export default function Layout({ children }: { children: ReactNode }) {
  return <SiteShell locale="${code}">{children}</SiteShell>;
}
`,
  );

  write(
    `${base}/page.tsx`,
    `
${banner}
import { HomePage, homeMetadata } from '@/components/pages';

export const metadata = homeMetadata('${code}');

export default function Page() {
  return <HomePage locale="${code}" />;
}
`,
  );

  // One static route per game rather than a [game] segment: static export
  // handles plain segments cleanly, whereas the dynamic form emits prefetch
  // payloads under paths the client never asks for (they 404 and fall back).
  for (const slug of GAME_SLUGS) {
    write(
      `${base}/${slug}/page.tsx`,
      `
${banner}
import { GamePage, gameMetadata } from '@/components/pages';

export const metadata = gameMetadata('${code}', '${slug}');

export default function Page() {
  return <GamePage locale="${code}" slug="${slug}" />;
}
`,
    );
  }

  for (const slug of PUZZLE_SLUGS) {
    write(
      `${base}/${slug}/puzzles/page.tsx`,
      `
${banner}
import { PuzzlePage, puzzleMetadata } from '@/components/pages';

export const metadata = puzzleMetadata('${code}', '${slug}');

export default function Page() {
  return <PuzzlePage locale="${code}" slug="${slug}" />;
}
`,
    );
  }

  write(
    `${base}/about/page.tsx`,
    `
${banner}
import { AboutPage, aboutMetadata } from '@/components/pages';

export const metadata = aboutMetadata('${code}');

export default function Page() {
  return <AboutPage locale="${code}" />;
}
`,
  );

  write(
    `${base}/privacy/page.tsx`,
    `
${banner}
import { PrivacyPage, privacyMetadata } from '@/components/pages';

export const metadata = privacyMetadata('${code}');

export default function Page() {
  return <PrivacyPage locale="${code}" />;
}
`,
  );
  write(
    `${base}/terms/page.tsx`,
    `
${banner}
import { TermsPage, termsMetadata } from '@/components/pages';

export const metadata = termsMetadata('${code}');

export default function Page() {
  return <TermsPage locale="${code}" />;
}
`,
  );

  write(
    `${base}/contact/page.tsx`,
    `
${banner}
import { ContactPage, contactMetadata } from '@/components/pages';

export const metadata = contactMetadata('${code}');

export default function Page() {
  return <ContactPage locale="${code}" />;
}
`,
  );
}

console.log('\nRoute files generated.');
