/**
 * Imports a curated slice of Lichess's open (CC0) puzzle database into
 * lib/puzzles/chess.ts. Streams the CSV from stdin so the ~250MB compressed
 * dump never has to be fully downloaded to disk:
 *
 *   curl -sL https://database.lichess.org/lichess_db_puzzle.csv.zst \
 *     | zstd -dc \
 *     | npx tsx scripts/import-chess-puzzles.ts
 *
 * CSV columns: PuzzleId,FEN,Moves,Rating,RatingDeviation,Popularity,NbPlays,
 * Themes,GameUrl,OpeningTags,DailyDate. `FEN` is the position *before* the
 * opponent's setup move (Moves[0]); the solver's line is Moves[1:], ending
 * in checkmate for mateIn1/2/3-themed rows.
 */
import * as readline from 'node:readline';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as chess from '../lib/games/chess';
import type { ChessPuzzle, PuzzleTier } from '../lib/puzzles/types';

const TIER_QUOTA = 30;
const BANDS: [number, number][] = [
  [0, 1199],
  [1200, 1799],
  [1800, Infinity],
];
const BAND_QUOTA = TIER_QUOTA / BANDS.length;
const MIN_POPULARITY = 50;

function algebraicToSquare(s: string): number {
  const file = s.charCodeAt(0) - 97;
  const rank = Number(s[1]);
  return chess.sq88(8 - rank, file);
}

const PROMO_CHAR: Record<string, number> = {
  q: chess.QUEEN,
  r: chess.ROOK,
  b: chess.BISHOP,
  n: chess.KNIGHT,
};

function uciToMove(uci: string): chess.ChessMove {
  const from = algebraicToSquare(uci.slice(0, 2));
  const to = algebraicToSquare(uci.slice(2, 4));
  const promo = uci.length > 4 ? PROMO_CHAR[uci[4]] : undefined;
  return promo ? { from, to, promo } : { from, to };
}

function movesEqual(a: chess.ChessMove, b: chess.ChessMove) {
  return a.from === b.from && a.to === b.to && (a.promo ?? 0) === (b.promo ?? 0);
}

function bandIndex(rating: number): number {
  return BANDS.findIndex(([lo, hi]) => rating >= lo && rating <= hi);
}

// quotas[tier][band]
const quotas: number[][] = [1, 2, 3].map(() => BANDS.map(() => BAND_QUOTA));
const results: ChessPuzzle[] = [];
let rows = 0;
let matched = 0;

function tierFromThemes(themes: string): PuzzleTier | null {
  if (themes.includes('mateIn1')) return 1;
  if (themes.includes('mateIn2')) return 2;
  if (themes.includes('mateIn3')) return 3;
  return null;
}

function quotasExhausted(): boolean {
  return quotas.every((byBand) => byBand.every((q) => q <= 0));
}

function tryImport(cols: string[]): ChessPuzzle | null {
  const [id, fen, movesStr, ratingStr, , popularityStr] = cols;
  const themes = cols[7] ?? '';
  const tier = tierFromThemes(themes);
  if (tier === null) return null;

  const rating = Number(ratingStr);
  const popularity = Number(popularityStr);
  if (!Number.isFinite(rating) || popularity < MIN_POPULARITY) return null;
  const band = bandIndex(rating);
  if (band < 0 || quotas[tier - 1][band] <= 0) return null;

  const uciMoves = movesStr.trim().split(' ');
  if (uciMoves.length !== 2 * tier) return null; // 1 setup move + (2*tier - 1) solution plies

  let state: chess.ChessState;
  try {
    state = chess.fromFen(fen);
  } catch {
    return null;
  }

  const setup = uciToMove(uciMoves[0]);
  if (!chess.legalMoves(state).some((m) => movesEqual(m, setup))) return null;
  const puzzleStart = chess.apply(state, setup);
  const solution = uciMoves.slice(1).map(uciToMove);

  let sim = puzzleStart;
  const solverSide = puzzleStart.turn;
  for (const mv of solution) {
    const legal = chess.legalMoves(sim);
    const match = legal.find((m) => movesEqual(m, mv));
    if (!match) return null;
    sim = chess.apply(sim, match);
  }
  const outcome = chess.outcome(sim);
  if (!outcome.over || outcome.reason !== 'checkmate' || outcome.winner !== solverSide) return null;

  return {
    id,
    sideToMove: solverSide,
    solution,
    setupMoves: [setup],
    fen,
    tier,
    source: 'lichess',
  };
}

const rl = readline.createInterface({ input: process.stdin, crlfDelay: Infinity });

rl.on('line', (line) => {
  rows++;
  if (rows === 1) return; // header
  if (quotasExhausted()) {
    rl.close();
    process.stdin.destroy();
    return;
  }
  const cols = line.split(',');
  if (cols.length < 8) return;
  const puzzle = tryImport(cols);
  if (!puzzle) return;
  const band = bandIndex(Number(cols[3]));
  quotas[puzzle.tier - 1][band]--;
  results.push(puzzle);
  matched++;
  if (matched % 10 === 0) console.log(`matched ${matched}/${TIER_QUOTA * 3} (scanned ${rows} rows)`);
});

rl.on('close', () => {
  const byTier = [1, 2, 3].map((t) => results.filter((p) => p.tier === t).length);
  console.log(`scanned ${rows} rows, kept ${results.length} (t1=${byTier[0]} t2=${byTier[1]} t3=${byTier[2]})`);

  const outFile = path.join(__dirname, '..', 'lib', 'puzzles', 'chess.ts');
  const body = `// Auto-generated by scripts/import-chess-puzzles.ts — do not hand-edit.\nimport type { ChessPuzzle } from './types';\n\nexport const CHESS_PUZZLES: ChessPuzzle[] = ${JSON.stringify(results, null, 2)};\n`;
  fs.writeFileSync(outFile, body);
  console.log(`wrote ${outFile}`);
});
