// Auto-generated by scripts/import-chess-puzzles.ts — do not hand-edit.
import type { ChessPuzzle } from './types';

export const CHESS_PUZZLES: ChessPuzzle[] = [
  {
    "id": "000Zo",
    "sideToMove": 2,
    "solution": [
      {
        "from": 4,
        "to": 116
      },
      {
        "from": 118,
        "to": 101
      },
      {
        "from": 116,
        "to": 117
      }
    ],
    "setupMoves": [
      {
        "from": 52,
        "to": 37
      }
    ],
    "fen": "4r3/1k6/pp3r2/1b2P2p/3R1p2/P1R2P2/1P4PP/6K1 w - - 0 35",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "000hf",
    "sideToMove": 1,
    "solution": [
      {
        "from": 100,
        "to": 36
      },
      {
        "from": 21,
        "to": 5
      },
      {
        "from": 36,
        "to": 21
      }
    ],
    "setupMoves": [
      {
        "from": 4,
        "to": 21
      }
    ],
    "fen": "r1bqk2r/pp1nbNp1/2p1p2p/8/2BP4/1PN3P1/P3QP1P/3R1RK1 b kq - 0 19",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "000rZ",
    "sideToMove": 2,
    "solution": [
      {
        "from": 35,
        "to": 103
      }
    ],
    "setupMoves": [
      {
        "from": 67,
        "to": 36
      }
    ],
    "fen": "2kr1b1r/p1p2pp1/2pqb3/7p/3N2n1/2NPB3/PPP2PPP/R2Q1RK1 w - - 2 13",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "001KR",
    "sideToMove": 1,
    "solution": [
      {
        "from": 117,
        "to": 5
      }
    ],
    "setupMoves": [
      {
        "from": 7,
        "to": 6
      }
    ],
    "fen": "6Qk/p1p3pp/4N3/1p6/2q1r1n1/2B5/PP4PP/3R1R1K b - - 0 28",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "001Wz",
    "sideToMove": 1,
    "solution": [
      {
        "from": 115,
        "to": 3
      },
      {
        "from": 52,
        "to": 4
      },
      {
        "from": 3,
        "to": 4
      }
    ],
    "setupMoves": [
      {
        "from": 4,
        "to": 52
      }
    ],
    "fen": "4r1k1/5ppp/r1p5/p1n1RP2/8/2P2N1P/2P3P1/3R2K1 b - - 0 21",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "001cr",
    "sideToMove": 1,
    "solution": [
      {
        "from": 19,
        "to": 4
      }
    ],
    "setupMoves": [
      {
        "from": 50,
        "to": 66
      }
    ],
    "fen": "8/3B2pp/p5k1/2p3P1/1p1p1K2/8/1P6/8 b - - 0 38",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "001gi",
    "sideToMove": 2,
    "solution": [
      {
        "from": 48,
        "to": 82
      }
    ],
    "setupMoves": [
      {
        "from": 18,
        "to": 0
      }
    ],
    "fen": "r6r/1pNk1ppp/2np4/b3p3/4P1b1/N1Q5/P4PPP/R3KB1R w KQ - 3 18",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "001om",
    "sideToMove": 2,
    "solution": [
      {
        "from": 50,
        "to": 101
      },
      {
        "from": 102,
        "to": 86
      },
      {
        "from": 101,
        "to": 86
      }
    ],
    "setupMoves": [
      {
        "from": 70,
        "to": 71
      }
    ],
    "fen": "5r1k/pp4pp/5p2/1BbQp1r1/6K1/7P/1PP3P1/3R3R w - - 2 26",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "001pC",
    "sideToMove": 2,
    "solution": [
      {
        "from": 87,
        "to": 101
      }
    ],
    "setupMoves": [
      {
        "from": 117,
        "to": 118
      }
    ],
    "fen": "r4rk1/pp3ppp/3b4/2p1pPB1/7N/2PP3n/PP4PP/R2Q1RqK w - - 5 18",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "001w5",
    "sideToMove": 1,
    "solution": [
      {
        "from": 98,
        "to": 23
      },
      {
        "from": 6,
        "to": 23
      },
      {
        "from": 22,
        "to": 6,
        "promo": 5
      }
    ],
    "setupMoves": [
      {
        "from": 5,
        "to": 21
      }
    ],
    "fen": "1rb2rk1/q5P1/4p2p/3p3p/3P1P2/2P5/2QK3P/3R2R1 b - - 0 29",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "001wR",
    "sideToMove": 1,
    "solution": [
      {
        "from": 65,
        "to": 48
      },
      {
        "from": 32,
        "to": 17
      },
      {
        "from": 66,
        "to": 35
      },
      {
        "from": 17,
        "to": 1
      },
      {
        "from": 48,
        "to": 3
      }
    ],
    "setupMoves": [
      {
        "from": 17,
        "to": 49
      }
    ],
    "fen": "6nr/pp3p1p/k1p5/8/1QN5/2P1P3/4KPqP/8 b - - 5 26",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "001wb",
    "sideToMove": 2,
    "solution": [
      {
        "from": 38,
        "to": 55
      }
    ],
    "setupMoves": [
      {
        "from": 103,
        "to": 86
      }
    ],
    "fen": "r3k2r/pb1p1ppp/1b4q1/1Q2P3/8/2NP1Pn1/PP4PP/R1B2R1K w kq - 1 17",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "002CP",
    "sideToMove": 2,
    "solution": [
      {
        "from": 38,
        "to": 98
      }
    ],
    "setupMoves": [
      {
        "from": 101,
        "to": 84
      }
    ],
    "fen": "r5k1/pp4pp/4p1q1/4p3/3n4/P5P1/1PP2Q1P/2KR1R2 w - - 4 24",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "002HE",
    "sideToMove": 2,
    "solution": [
      {
        "from": 1,
        "to": 86
      }
    ],
    "setupMoves": [
      {
        "from": 118,
        "to": 101
      }
    ],
    "fen": "1qr2rk1/1p1p1ppp/pB2p1n1/7n/2P1P3/1Q2NP1P/PP2B1Pb/3R1RK1 w - - 1 20",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "002Mm",
    "sideToMove": 1,
    "solution": [
      {
        "from": 23,
        "to": 7
      },
      {
        "from": 5,
        "to": 20
      },
      {
        "from": 7,
        "to": 22
      }
    ],
    "setupMoves": [
      {
        "from": 6,
        "to": 5
      }
    ],
    "fen": "rn1qr1k1/ppp3pQ/3p1pP1/3Pp3/2P1P3/8/PP3PP1/R1B1K3 b Q - 2 16",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "002Q2",
    "sideToMove": 2,
    "solution": [
      {
        "from": 53,
        "to": 86
      }
    ],
    "setupMoves": [
      {
        "from": 69,
        "to": 39
      }
    ],
    "fen": "7k/p4R1p/3p3r/2pN1n2/2PbBBb1/3P2P1/P3r3/5R1K w - - 1 28",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "002X3",
    "sideToMove": 1,
    "solution": [
      {
        "from": 102,
        "to": 0
      },
      {
        "from": 18,
        "to": 1
      },
      {
        "from": 0,
        "to": 1
      }
    ],
    "setupMoves": [
      {
        "from": 81,
        "to": 80
      }
    ],
    "fen": "6k1/2q2p1p/4pPp1/4P3/p1pP1P2/RrP5/6QP/4B1K1 b - - 0 33",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "002Z9",
    "sideToMove": 1,
    "solution": [
      {
        "from": 20,
        "to": 4
      }
    ],
    "setupMoves": [
      {
        "from": 69,
        "to": 99
      }
    ],
    "fen": "4r1k1/1p2R1p1/p2p2Pp/P1pP4/5q2/1R3p2/1P1Q3P/5B1K b - - 0 34",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "002p5",
    "sideToMove": 1,
    "solution": [
      {
        "from": 98,
        "to": 23
      },
      {
        "from": 6,
        "to": 5
      },
      {
        "from": 23,
        "to": 7
      }
    ],
    "setupMoves": [
      {
        "from": 37,
        "to": 51
      }
    ],
    "fen": "r1bqr1k1/pp1nbpp1/2p2n2/6P1/2BP4/P7/1PQNNPP1/R3K2R b KQ - 0 13",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "002vV",
    "sideToMove": 2,
    "solution": [
      {
        "from": 112,
        "to": 119
      }
    ],
    "setupMoves": [
      {
        "from": 34,
        "to": 33
      }
    ],
    "fen": "8/6k1/2R4p/5p1P/5P1K/6P1/8/r7 w - - 2 58",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "0030b",
    "sideToMove": 1,
    "solution": [
      {
        "from": 115,
        "to": 3
      },
      {
        "from": 37,
        "to": 4
      },
      {
        "from": 3,
        "to": 4
      }
    ],
    "setupMoves": [
      {
        "from": 38,
        "to": 68
      }
    ],
    "fen": "6k1/5ppp/5nb1/pp6/6rP/5N1Q/Pq2r1P1/3R2RK b - - 4 32",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "003AX",
    "sideToMove": 1,
    "solution": [
      {
        "from": 98,
        "to": 23
      }
    ],
    "setupMoves": [
      {
        "from": 50,
        "to": 67
      }
    ],
    "fen": "2r2rk1/5ppp/bq2p3/p1ppP1N1/Pb1P2P1/1P2P2P/2QN4/2R1K2R b K - 1 18",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "003IX",
    "sideToMove": 2,
    "solution": [
      {
        "from": 68,
        "to": 86
      }
    ],
    "setupMoves": [
      {
        "from": 69,
        "to": 53
      }
    ],
    "fen": "8/3pk3/R7/1R2Pp1p/2PPnKr1/8/8/8 w - - 4 43",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "003Tx",
    "sideToMove": 2,
    "solution": [
      {
        "from": 85,
        "to": 99
      },
      {
        "from": 113,
        "to": 112
      },
      {
        "from": 2,
        "to": 114
      }
    ],
    "setupMoves": [
      {
        "from": 116,
        "to": 68
      }
    ],
    "fen": "2r5/pR5p/5p1k/4p3/4r3/B4nPP/PP3P2/1K2R3 w - - 0 27",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "0042j",
    "sideToMove": 1,
    "solution": [
      {
        "from": 99,
        "to": 3
      },
      {
        "from": 33,
        "to": 3
      },
      {
        "from": 115,
        "to": 3
      }
    ],
    "setupMoves": [
      {
        "from": 35,
        "to": 52
      }
    ],
    "fen": "3r2k1/4nppp/pq1p1b2/1p2P3/2r2P2/2P1NR2/PP1Q2BP/3R2K1 b - - 0 24",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "004JD",
    "sideToMove": 2,
    "solution": [
      {
        "from": 80,
        "to": 98
      }
    ],
    "setupMoves": [
      {
        "from": 99,
        "to": 84
      }
    ],
    "fen": "3r4/R7/2p5/p1P2p2/1p4k1/nP6/P2KNP2/8 w - - 3 41",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "004X6",
    "sideToMove": 2,
    "solution": [
      {
        "from": 1,
        "to": 113
      },
      {
        "from": 99,
        "to": 115
      },
      {
        "from": 113,
        "to": 115
      }
    ],
    "setupMoves": [
      {
        "from": 112,
        "to": 113
      }
    ],
    "fen": "1r4k1/p4ppp/2Q5/3pq3/8/P6P/2PR1PP1/Rr4K1 w - - 1 26",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "004XI",
    "sideToMove": 1,
    "solution": [
      {
        "from": 113,
        "to": 17
      },
      {
        "from": 19,
        "to": 4
      },
      {
        "from": 114,
        "to": 2
      }
    ],
    "setupMoves": [
      {
        "from": 20,
        "to": 80
      }
    ],
    "fen": "8/3kqp2/4p3/p2p4/3P1P2/4P1rP/7r/1QR2K2 b - - 1 34",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "004kB",
    "sideToMove": 2,
    "solution": [
      {
        "from": 37,
        "to": 101
      },
      {
        "from": 117,
        "to": 101
      },
      {
        "from": 4,
        "to": 116
      },
      {
        "from": 101,
        "to": 117
      },
      {
        "from": 116,
        "to": 117
      }
    ],
    "setupMoves": [
      {
        "from": 17,
        "to": 18
      }
    ],
    "fen": "4rr1k/pQpn2pp/3p1q2/8/8/2P5/PP3PPP/RN3RK1 w - - 1 16",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "004zI",
    "sideToMove": 1,
    "solution": [
      {
        "from": 39,
        "to": 7
      }
    ],
    "setupMoves": [
      {
        "from": 23,
        "to": 38
      }
    ],
    "fen": "2q3k1/4br1p/6RQ/1p1n2p1/7P/1P4P1/1B2PP2/6K1 b - - 0 27",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "005Bm",
    "sideToMove": 1,
    "solution": [
      {
        "from": 71,
        "to": 38
      },
      {
        "from": 5,
        "to": 6
      },
      {
        "from": 37,
        "to": 7
      }
    ],
    "setupMoves": [
      {
        "from": 18,
        "to": 21
      }
    ],
    "fen": "4rk2/p1q5/1p3Q1b/8/1p5N/2P1p3/P3P3/2K5 b - - 0 43",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "005wJ",
    "sideToMove": 2,
    "solution": [
      {
        "from": 18,
        "to": 114
      }
    ],
    "setupMoves": [
      {
        "from": 52,
        "to": 19
      }
    ],
    "fen": "r3kb1r/ppqn1ppp/4pn2/1Q2Nb2/3P4/8/PP2PPPP/RNB1KB1R w KQkq - 4 9",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "005wy",
    "sideToMove": 2,
    "solution": [
      {
        "from": 34,
        "to": 65
      },
      {
        "from": 82,
        "to": 65
      },
      {
        "from": 1,
        "to": 2
      },
      {
        "from": 99,
        "to": 66
      },
      {
        "from": 2,
        "to": 66
      }
    ],
    "setupMoves": [
      {
        "from": 55,
        "to": 23
      }
    ],
    "fen": "1r6/pp2kpp1/2n1p1n1/3p2PQ/5P2/2PqP3/PP1N4/2KR3R w - - 3 27",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "006pe",
    "sideToMove": 1,
    "solution": [
      {
        "from": 20,
        "to": 53
      },
      {
        "from": 39,
        "to": 23
      },
      {
        "from": 37,
        "to": 22
      }
    ],
    "setupMoves": [
      {
        "from": 36,
        "to": 21
      }
    ],
    "fen": "r4r2/2q1NN2/4bQpk/2n4p/pp5P/8/1PP2PP1/2KR3R b - - 0 28",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "007en",
    "sideToMove": 2,
    "solution": [
      {
        "from": 50,
        "to": 98
      },
      {
        "from": 113,
        "to": 112
      },
      {
        "from": 0,
        "to": 80
      },
      {
        "from": 97,
        "to": 80
      },
      {
        "from": 98,
        "to": 96
      }
    ],
    "setupMoves": [
      {
        "from": 84,
        "to": 67
      }
    ],
    "fen": "rn3rk1/4pp1p/3p2pB/2q4P/3bP1b1/Pp2Q3/1P2B3/1K1R2NR w - - 0 20",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "007ku",
    "sideToMove": 1,
    "solution": [
      {
        "from": 7,
        "to": 55
      },
      {
        "from": 38,
        "to": 37
      },
      {
        "from": 69,
        "to": 54
      }
    ],
    "setupMoves": [
      {
        "from": 21,
        "to": 38
      }
    ],
    "fen": "r1bq3Q/1np2kp1/p5B1/1p1Pp3/1Pn2BP1/2b2P2/P3K3/R4N2 b - - 5 35",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "009BH",
    "sideToMove": 1,
    "solution": [
      {
        "from": 36,
        "to": 39
      },
      {
        "from": 7,
        "to": 6
      },
      {
        "from": 39,
        "to": 22
      }
    ],
    "setupMoves": [
      {
        "from": 6,
        "to": 7
      }
    ],
    "fen": "3r2k1/6p1/4Q3/4B3/1p3P2/4PKP1/3q4/8 b - - 17 51",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "009J1",
    "sideToMove": 1,
    "solution": [
      {
        "from": 54,
        "to": 39
      }
    ],
    "setupMoves": [
      {
        "from": 4,
        "to": 5
      }
    ],
    "fen": "rn2k2r/pp2bp1p/2p1pNp1/6B1/5P2/7P/PPP4P/2K1RR2 b - - 3 17",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "009wR",
    "sideToMove": 2,
    "solution": [
      {
        "from": 101,
        "to": 117
      },
      {
        "from": 119,
        "to": 102
      },
      {
        "from": 117,
        "to": 118
      }
    ],
    "setupMoves": [
      {
        "from": 102,
        "to": 119
      }
    ],
    "fen": "1R2R3/p7/1p1k3p/1Pb5/P5p1/6P1/5rKP/8 w - - 6 41",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "009zR",
    "sideToMove": 2,
    "solution": [
      {
        "from": 99,
        "to": 85
      },
      {
        "from": 118,
        "to": 119
      },
      {
        "from": 98,
        "to": 102
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 3
      }
    ],
    "fen": "3r4/p1p2ppp/4k3/6Q1/5P2/4P3/Prqn2PP/3R1RK1 w - - 3 22",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00Aq4",
    "sideToMove": 2,
    "solution": [
      {
        "from": 4,
        "to": 116
      },
      {
        "from": 99,
        "to": 115
      },
      {
        "from": 35,
        "to": 69
      },
      {
        "from": 114,
        "to": 113
      },
      {
        "from": 116,
        "to": 115
      }
    ],
    "setupMoves": [
      {
        "from": 66,
        "to": 51
      }
    ],
    "fen": "2k1r3/pppn1pp1/3b2b1/3p2Pp/2B2P2/3P3P/PPPR4/2K3NR w - - 0 18",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00Bg4",
    "sideToMove": 1,
    "solution": [
      {
        "from": 48,
        "to": 3
      },
      {
        "from": 51,
        "to": 3
      },
      {
        "from": 115,
        "to": 3
      }
    ],
    "setupMoves": [
      {
        "from": 35,
        "to": 51
      }
    ],
    "fen": "3r2k1/1q3ppp/p2rp3/Qp1B4/7P/P4P2/1PP3P1/1K1R3R b - - 0 21",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00BrZ",
    "sideToMove": 2,
    "solution": [
      {
        "from": 7,
        "to": 103
      },
      {
        "from": 119,
        "to": 103
      },
      {
        "from": 0,
        "to": 7
      },
      {
        "from": 99,
        "to": 39
      },
      {
        "from": 7,
        "to": 39
      }
    ],
    "setupMoves": [
      {
        "from": 39,
        "to": 99
      }
    ],
    "fen": "r6r/pp2kb2/3p1p1Q/1N1Pp3/3bP3/P2B2P1/1P4PP/7K w - - 6 28",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00CBU",
    "sideToMove": 1,
    "solution": [
      {
        "from": 80,
        "to": 5
      },
      {
        "from": 39,
        "to": 55
      },
      {
        "from": 19,
        "to": 23
      }
    ],
    "setupMoves": [
      {
        "from": 22,
        "to": 39
      }
    ],
    "fen": "8/2pR2kp/pb4p1/8/5p1P/B6K/P1r5/6r1 b - - 3 39",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00CWE",
    "sideToMove": 1,
    "solution": [
      {
        "from": 38,
        "to": 21
      }
    ],
    "setupMoves": [
      {
        "from": 36,
        "to": 51
      }
    ],
    "fen": "3r4/1p4p1/2pBkbBp/p1P5/3rp3/P7/1PK2P2/4R3 b - - 1 31",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "00F6y",
    "sideToMove": 1,
    "solution": [
      {
        "from": 84,
        "to": 4
      },
      {
        "from": 19,
        "to": 4
      },
      {
        "from": 116,
        "to": 4
      },
      {
        "from": 6,
        "to": 4
      },
      {
        "from": 64,
        "to": 4
      }
    ],
    "setupMoves": [
      {
        "from": 36,
        "to": 19
      }
    ],
    "fen": "2k3r1/ppp2prp/1q2b3/8/Q7/2P1R1P1/P4P1P/4R1K1 b - - 3 23",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00FND",
    "sideToMove": 2,
    "solution": [
      {
        "from": 83,
        "to": 84
      },
      {
        "from": 87,
        "to": 71
      },
      {
        "from": 85,
        "to": 101
      }
    ],
    "setupMoves": [
      {
        "from": 115,
        "to": 116
      }
    ],
    "fen": "8/1P6/8/7p/3P4/3k1p1P/4p3/3K4 w - - 0 49",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00GuD",
    "sideToMove": 1,
    "solution": [
      {
        "from": 119,
        "to": 39
      },
      {
        "from": 22,
        "to": 39
      },
      {
        "from": 38,
        "to": 22
      },
      {
        "from": 7,
        "to": 23
      },
      {
        "from": 22,
        "to": 6,
        "promo": 5
      }
    ],
    "setupMoves": [
      {
        "from": 20,
        "to": 100
      }
    ],
    "fen": "1n5k/4r1p1/p2q1rPp/1ppB4/8/3P4/PPP1RPQ1/2K4R b - - 4 25",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00Gv1",
    "sideToMove": 2,
    "solution": [
      {
        "from": 36,
        "to": 116
      },
      {
        "from": 115,
        "to": 116
      },
      {
        "from": 20,
        "to": 116
      },
      {
        "from": 118,
        "to": 101
      },
      {
        "from": 87,
        "to": 117
      }
    ],
    "setupMoves": [
      {
        "from": 99,
        "to": 3
      }
    ],
    "fen": "8/1pp1r1kp/4r1p1/p1P5/5Q2/P4PPq/1P1R3P/3R2K1 w - - 2 32",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00H1C",
    "sideToMove": 1,
    "solution": [
      {
        "from": 48,
        "to": 18
      }
    ],
    "setupMoves": [
      {
        "from": 20,
        "to": 34
      }
    ],
    "fen": "r3r3/1kpRnqpp/p4p2/Qp2P2P/1N6/4Pb2/PPP3P1/2K2R2 b - - 0 22",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "00HJd",
    "sideToMove": 1,
    "solution": [
      {
        "from": 66,
        "to": 21
      }
    ],
    "setupMoves": [
      {
        "from": 51,
        "to": 69
      }
    ],
    "fen": "r1bqkb1r/pp2pppp/2p2n2/2PnN3/2BP1B2/8/PP3PPP/RN1QR1K1 b kq - 2 12",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "00Ivf",
    "sideToMove": 2,
    "solution": [
      {
        "from": 87,
        "to": 103
      },
      {
        "from": 102,
        "to": 117
      },
      {
        "from": 103,
        "to": 119
      },
      {
        "from": 117,
        "to": 101
      },
      {
        "from": 23,
        "to": 103
      }
    ],
    "setupMoves": [
      {
        "from": 68,
        "to": 52
      }
    ],
    "fen": "8/2p4r/1p3k2/p2Pp1p1/P1P1RpP1/1P3P1r/4R1K1/8 w - - 7 46",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00J1t",
    "sideToMove": 1,
    "solution": [
      {
        "from": 99,
        "to": 54
      },
      {
        "from": 3,
        "to": 6
      },
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 22,
        "to": 39
      },
      {
        "from": 55,
        "to": 39
      }
    ],
    "setupMoves": [
      {
        "from": 37,
        "to": 22
      }
    ],
    "fen": "r1qr3k/pp3pB1/1np1pb2/8/3P3P/2N2PR1/PP1Q2P1/2KR4 b - - 0 22",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00JR7",
    "sideToMove": 1,
    "solution": [
      {
        "from": 83,
        "to": 23
      },
      {
        "from": 6,
        "to": 21
      },
      {
        "from": 98,
        "to": 38
      },
      {
        "from": 21,
        "to": 5
      },
      {
        "from": 23,
        "to": 7
      }
    ],
    "setupMoves": [
      {
        "from": 5,
        "to": 85
      }
    ],
    "fen": "r4rk1/pp2q1p1/2p1p2p/3nP1pP/3P2P1/2PQ1R2/PPB5/R5K1 b - - 1 23",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00JsQ",
    "sideToMove": 1,
    "solution": [
      {
        "from": 99,
        "to": 3
      },
      {
        "from": 4,
        "to": 21
      },
      {
        "from": 3,
        "to": 5
      }
    ],
    "setupMoves": [
      {
        "from": 19,
        "to": 50
      }
    ],
    "fen": "r1b1k1nr/pp1np2p/2q1Npp1/2P1p3/2B5/2N3B1/PPPR1PPP/2K4R b kq - 2 14",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00Kbj",
    "sideToMove": 2,
    "solution": [
      {
        "from": 69,
        "to": 86
      },
      {
        "from": 49,
        "to": 51
      },
      {
        "from": 96,
        "to": 112
      },
      {
        "from": 51,
        "to": 115
      },
      {
        "from": 112,
        "to": 115
      }
    ],
    "setupMoves": [
      {
        "from": 87,
        "to": 71
      }
    ],
    "fen": "8/8/6p1/PR3p2/1P3k2/7P/r5P1/7K w - - 1 39",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00Kyy",
    "sideToMove": 2,
    "solution": [
      {
        "from": 86,
        "to": 87
      },
      {
        "from": 119,
        "to": 118
      },
      {
        "from": 101,
        "to": 102
      },
      {
        "from": 118,
        "to": 117
      },
      {
        "from": 87,
        "to": 119
      }
    ],
    "setupMoves": [
      {
        "from": 16,
        "to": 0,
        "promo": 5
      }
    ],
    "fen": "8/P7/8/5k2/8/5pr1/5r2/R6K w - - 0 50",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00MDG",
    "sideToMove": 1,
    "solution": [
      {
        "from": 101,
        "to": 21
      },
      {
        "from": 6,
        "to": 7
      },
      {
        "from": 21,
        "to": 5
      },
      {
        "from": 3,
        "to": 5
      },
      {
        "from": 117,
        "to": 5
      }
    ],
    "setupMoves": [
      {
        "from": 36,
        "to": 68
      }
    ],
    "fen": "3r2k1/4ppnp/pp2q1p1/2p5/4N3/3rP3/P2P1QPP/3R1RK1 b - - 1 28",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00NEO",
    "sideToMove": 1,
    "solution": [
      {
        "from": 87,
        "to": 39
      },
      {
        "from": 23,
        "to": 6
      },
      {
        "from": 39,
        "to": 22
      }
    ],
    "setupMoves": [
      {
        "from": 19,
        "to": 34
      }
    ],
    "fen": "4qr2/pR1b2pk/5p1p/4pPP1/3bB3/3P3Q/P1r4P/4BR1K b - - 0 24",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00NHK",
    "sideToMove": 1,
    "solution": [
      {
        "from": 119,
        "to": 7
      },
      {
        "from": 6,
        "to": 7
      },
      {
        "from": 115,
        "to": 55
      },
      {
        "from": 7,
        "to": 6
      },
      {
        "from": 55,
        "to": 23
      }
    ],
    "setupMoves": [
      {
        "from": 34,
        "to": 52
      }
    ],
    "fen": "r1b2rk1/1p2b1p1/pqn1p1P1/3pP3/1P1P4/P1N1P3/6P1/R2QK2R b KQ - 0 17",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00O9a",
    "sideToMove": 2,
    "solution": [
      {
        "from": 16,
        "to": 101
      },
      {
        "from": 118,
        "to": 119
      },
      {
        "from": 101,
        "to": 117
      },
      {
        "from": 112,
        "to": 117
      },
      {
        "from": 5,
        "to": 117
      }
    ],
    "setupMoves": [
      {
        "from": 48,
        "to": 66
      }
    ],
    "fen": "1k3r2/q5r1/2Qp3p/N2Bp3/4P1p1/P7/1PP2PPP/R5K1 w - - 12 35",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00Pbs",
    "sideToMove": 2,
    "solution": [
      {
        "from": 51,
        "to": 102
      },
      {
        "from": 117,
        "to": 116
      },
      {
        "from": 71,
        "to": 85
      }
    ],
    "setupMoves": [
      {
        "from": 16,
        "to": 20
      }
    ],
    "fen": "3r1rk1/Q3qppp/8/1ppb4/2Pn1B1n/2N3P1/PP3P2/R2R1K2 w - - 0 21",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00QHM",
    "sideToMove": 1,
    "solution": [
      {
        "from": 114,
        "to": 2
      },
      {
        "from": 37,
        "to": 3
      },
      {
        "from": 2,
        "to": 3
      },
      {
        "from": 21,
        "to": 5
      },
      {
        "from": 3,
        "to": 5
      }
    ],
    "setupMoves": [
      {
        "from": 67,
        "to": 65
      }
    ],
    "fen": "6k1/pp3rpp/4Nb2/4p3/1B1r4/6PK/PP5P/2R5 b - - 0 28",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00QW1",
    "sideToMove": 2,
    "solution": [
      {
        "from": 99,
        "to": 115
      },
      {
        "from": 114,
        "to": 97
      },
      {
        "from": 19,
        "to": 99
      },
      {
        "from": 97,
        "to": 80
      },
      {
        "from": 115,
        "to": 112
      }
    ],
    "setupMoves": [
      {
        "from": 98,
        "to": 114
      }
    ],
    "fen": "8/3r1ppp/4p3/k3P3/pR2R2P/2P5/2Kr1PP1/8 w - - 4 31",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00Se9",
    "sideToMove": 1,
    "solution": [
      {
        "from": 38,
        "to": 20
      },
      {
        "from": 6,
        "to": 22
      },
      {
        "from": 51,
        "to": 54
      }
    ],
    "setupMoves": [
      {
        "from": 22,
        "to": 21
      }
    ],
    "fen": "5rk1/pp1n2r1/3p2N1/2pQ4/2P5/4P1P1/qP2KPP1/7R b - - 1 24",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00TJN",
    "sideToMove": 1,
    "solution": [
      {
        "from": 85,
        "to": 21
      },
      {
        "from": 6,
        "to": 21
      },
      {
        "from": 51,
        "to": 19
      }
    ],
    "setupMoves": [
      {
        "from": 53,
        "to": 113
      }
    ],
    "fen": "r3r1k1/pp3pB1/2q3pp/3R1b2/8/P4Q2/BP3PPP/1R4K1 b - - 0 23",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00Wyh",
    "sideToMove": 1,
    "solution": [
      {
        "from": 98,
        "to": 99
      },
      {
        "from": 83,
        "to": 68
      },
      {
        "from": 49,
        "to": 35
      }
    ],
    "setupMoves": [
      {
        "from": 67,
        "to": 83
      }
    ],
    "fen": "2r5/8/8/pNp1r2p/3kNppP/1P1P4/2R2K2/8 b - - 2 42",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00Ycz",
    "sideToMove": 2,
    "solution": [
      {
        "from": 98,
        "to": 101
      },
      {
        "from": 118,
        "to": 119
      },
      {
        "from": 101,
        "to": 117
      },
      {
        "from": 116,
        "to": 117
      },
      {
        "from": 21,
        "to": 117
      }
    ],
    "setupMoves": [
      {
        "from": 37,
        "to": 36
      }
    ],
    "fen": "5k2/5r1p/pp2pQ2/8/8/1P6/P1q2PPP/4R1K1 w - - 1 32",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00bpH",
    "sideToMove": 1,
    "solution": [
      {
        "from": 114,
        "to": 69
      },
      {
        "from": 70,
        "to": 55
      },
      {
        "from": 69,
        "to": 53
      }
    ],
    "setupMoves": [
      {
        "from": 55,
        "to": 70
      }
    ],
    "fen": "8/5p2/pq5p/1p5k/6B1/6P1/P6P/2Q4K b - - 0 36",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00cxG",
    "sideToMove": 2,
    "solution": [
      {
        "from": 69,
        "to": 114
      },
      {
        "from": 97,
        "to": 96
      },
      {
        "from": 2,
        "to": 98
      }
    ],
    "setupMoves": [
      {
        "from": 98,
        "to": 97
      }
    ],
    "fen": "2r5/3RQ2p/6pk/8/5q1P/1P6/2K5/8 w - - 16 42",
    "tier": 2,
    "source": "lichess"
  },
  {
    "id": "00d5g",
    "sideToMove": 1,
    "solution": [
      {
        "from": 117,
        "to": 119
      },
      {
        "from": 2,
        "to": 87
      },
      {
        "from": 119,
        "to": 87
      },
      {
        "from": 52,
        "to": 55
      },
      {
        "from": 87,
        "to": 55
      }
    ],
    "setupMoves": [
      {
        "from": 6,
        "to": 7
      }
    ],
    "fen": "2b2rk1/pp4p1/2p5/4r3/2B5/1P6/P4pK1/5R2 b - - 4 32",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00dt1",
    "sideToMove": 2,
    "solution": [
      {
        "from": 67,
        "to": 49
      },
      {
        "from": 80,
        "to": 96
      },
      {
        "from": 49,
        "to": 82
      },
      {
        "from": 96,
        "to": 112
      },
      {
        "from": 65,
        "to": 113
      }
    ],
    "setupMoves": [
      {
        "from": 64,
        "to": 80
      }
    ],
    "fen": "Q7/8/3B4/2p5/Krkn4/8/8/8 w - - 1 54",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00fxc",
    "sideToMove": 2,
    "solution": [
      {
        "from": 4,
        "to": 84
      },
      {
        "from": 85,
        "to": 70
      },
      {
        "from": 83,
        "to": 52
      },
      {
        "from": 70,
        "to": 55
      },
      {
        "from": 100,
        "to": 103
      }
    ],
    "setupMoves": [
      {
        "from": 18,
        "to": 21
      }
    ],
    "fen": "4r2k/1pQ2p2/p4N1p/5P2/1P6/P1Pn1K2/4r3/6R1 w - - 1 36",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00nsa",
    "sideToMove": 2,
    "solution": [
      {
        "from": 68,
        "to": 70
      },
      {
        "from": 54,
        "to": 39
      },
      {
        "from": 70,
        "to": 71
      },
      {
        "from": 86,
        "to": 71
      },
      {
        "from": 52,
        "to": 69
      }
    ],
    "setupMoves": [
      {
        "from": 33,
        "to": 50
      }
    ],
    "fen": "6k1/1p1R3p/pB4p1/P3bpK1/4r2P/6P1/2P2P2/8 w - - 3 34",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00rHa",
    "sideToMove": 2,
    "solution": [
      {
        "from": 64,
        "to": 98
      },
      {
        "from": 67,
        "to": 98
      },
      {
        "from": 80,
        "to": 81
      },
      {
        "from": 113,
        "to": 112
      },
      {
        "from": 65,
        "to": 98
      }
    ],
    "setupMoves": [
      {
        "from": 117,
        "to": 49
      }
    ],
    "fen": "2kr3r/pp2nppp/4p3/2PpP3/bn1N2Q1/q1N5/2PB1PPP/1K1R1B1R w - - 4 14",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "00vuv",
    "sideToMove": 1,
    "solution": [
      {
        "from": 38,
        "to": 5
      },
      {
        "from": 23,
        "to": 6
      },
      {
        "from": 53,
        "to": 23
      },
      {
        "from": 6,
        "to": 5
      },
      {
        "from": 23,
        "to": 7
      }
    ],
    "setupMoves": [
      {
        "from": 83,
        "to": 99
      }
    ],
    "fen": "r3r3/2q1b1pk/p3P1Np/5Qp1/8/3p4/PPp2P2/2R1R1K1 b - - 1 30",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "010WS",
    "sideToMove": 2,
    "solution": [
      {
        "from": 69,
        "to": 100
      },
      {
        "from": 118,
        "to": 119
      },
      {
        "from": 67,
        "to": 115
      },
      {
        "from": 101,
        "to": 117
      },
      {
        "from": 115,
        "to": 117
      }
    ],
    "setupMoves": [
      {
        "from": 98,
        "to": 101
      }
    ],
    "fen": "6k1/p2Q4/3p2p1/8/3qPn2/5P2/PPR3PP/6K1 w - - 2 37",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "011GG",
    "sideToMove": 2,
    "solution": [
      {
        "from": 99,
        "to": 98
      },
      {
        "from": 114,
        "to": 113
      },
      {
        "from": 98,
        "to": 97
      },
      {
        "from": 113,
        "to": 112
      },
      {
        "from": 97,
        "to": 103
      }
    ],
    "setupMoves": [
      {
        "from": 113,
        "to": 114
      }
    ],
    "fen": "1R1Q4/5ppk/7p/4Pb2/1P6/2b5/3r3P/1K1R4 w - - 3 36",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "016rF",
    "sideToMove": 1,
    "solution": [
      {
        "from": 83,
        "to": 23
      },
      {
        "from": 6,
        "to": 5
      },
      {
        "from": 23,
        "to": 7
      },
      {
        "from": 5,
        "to": 20
      },
      {
        "from": 82,
        "to": 51
      }
    ],
    "setupMoves": [
      {
        "from": 5,
        "to": 37
      }
    ],
    "fen": "r4qk1/pppb2p1/1bnp1R2/6N1/8/2NQ2B1/PP4PP/7K b - - 0 19",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "019gx",
    "sideToMove": 2,
    "solution": [
      {
        "from": 66,
        "to": 64
      },
      {
        "from": 48,
        "to": 64
      },
      {
        "from": 1,
        "to": 0
      },
      {
        "from": 22,
        "to": 16
      },
      {
        "from": 0,
        "to": 16
      }
    ],
    "setupMoves": [
      {
        "from": 64,
        "to": 48
      }
    ],
    "fen": "1r6/6R1/3p4/1P1Rp3/K1r1P3/2k2P2/8/8 w - - 1 45",
    "tier": 3,
    "source": "lichess"
  },
  {
    "id": "01a5v",
    "sideToMove": 2,
    "solution": [
      {
        "from": 102,
        "to": 103
      }
    ],
    "setupMoves": [
      {
        "from": 69,
        "to": 54
      }
    ],
    "fen": "4r2k/R7/1p6/5ppp/3P1P1K/4P3/PP2QPq1/2R5 w - - 0 32",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "020Gj",
    "sideToMove": 2,
    "solution": [
      {
        "from": 33,
        "to": 101
      }
    ],
    "setupMoves": [
      {
        "from": 83,
        "to": 68
      }
    ],
    "fen": "r4r1k/ppp1N1pp/1b1p1p2/8/8/2PB1q1b/P1QB1P1P/R3R1K1 w - - 0 21",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "02Am1",
    "sideToMove": 2,
    "solution": [
      {
        "from": 69,
        "to": 102
      }
    ],
    "setupMoves": [
      {
        "from": 18,
        "to": 2,
        "promo": 5
      }
    ],
    "fen": "8/2P1R3/5k2/1B1p4/N2Ppn2/4K3/2r5/8 w - - 1 54",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "04OzC",
    "sideToMove": 2,
    "solution": [
      {
        "from": 100,
        "to": 102
      }
    ],
    "setupMoves": [
      {
        "from": 70,
        "to": 103
      }
    ],
    "fen": "8/5kpp/pp1Q1p2/8/P2P2N1/1P3P2/2r1q2r/1R2R2K w - - 0 35",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "04cDV",
    "sideToMove": 1,
    "solution": [
      {
        "from": 86,
        "to": 35
      }
    ],
    "setupMoves": [
      {
        "from": 5,
        "to": 20
      }
    ],
    "fen": "r4k1r/pp2Bppp/4nq2/1B6/8/2b3QP/P4PP1/3R1RK1 b - - 0 18",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "04hNd",
    "sideToMove": 1,
    "solution": [
      {
        "from": 54,
        "to": 55
      }
    ],
    "setupMoves": [
      {
        "from": 51,
        "to": 83
      }
    ],
    "fen": "8/7p/2p5/3q1pQ1/4p3/5kPP/3P1P2/6K1 b - - 2 35",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "05CzU",
    "sideToMove": 1,
    "solution": [
      {
        "from": 21,
        "to": 5
      }
    ],
    "setupMoves": [
      {
        "from": 2,
        "to": 17
      }
    ],
    "fen": "r1b3k1/p2p1R1p/1p4pB/1P6/2Bbq3/8/P5PP/2R4K b - - 0 27",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "06CZp",
    "sideToMove": 2,
    "solution": [
      {
        "from": 20,
        "to": 71
      }
    ],
    "setupMoves": [
      {
        "from": 68,
        "to": 53
      }
    ],
    "fen": "2kr3r/pppbq3/2np4/2bB1p1p/PP2P1pP/2PP4/6PK/RNBQ1R2 w - - 0 16",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "07mts",
    "sideToMove": 2,
    "solution": [
      {
        "from": 70,
        "to": 103
      }
    ],
    "setupMoves": [
      {
        "from": 118,
        "to": 117
      }
    ],
    "fen": "6k1/pbp2pp1/3p3p/2p5/2P3nB/1P5P/PQP3r1/4R1K1 w - - 0 24",
    "tier": 1,
    "source": "lichess"
  },
  {
    "id": "07p1C",
    "sideToMove": 2,
    "solution": [
      {
        "from": 36,
        "to": 66
      }
    ],
    "setupMoves": [
      {
        "from": 69,
        "to": 87
      }
    ],
    "fen": "1r2r1k1/5p1p/4b1p1/2p5/1n1b1N2/1P3PPq/P2BK2P/1BRQ3R w - - 9 23",
    "tier": 1,
    "source": "lichess"
  }
];
