// Auto-generated by scripts/gen-puzzles.ts — do not hand-edit.
import type { JanggiPuzzle } from './types';

export const JANGGI_PUZZLES: JanggiPuzzle[] = [
  {
    "id": "janggi-t1-1",
    "sideToMove": 2,
    "solution": [
      {
        "from": 83,
        "to": 65
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 45
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 82,
        "to": 65
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 64,
        "to": 66
      },
      {
        "from": 7,
        "to": 26
      },
      {
        "from": 56,
        "to": 57
      },
      {
        "from": 3,
        "to": 4
      },
      {
        "from": 81,
        "to": 82
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 45,
        "to": 46
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 44,
        "to": 41
      },
      {
        "from": 58,
        "to": 59
      },
      {
        "from": 19,
        "to": 22
      },
      {
        "from": 70,
        "to": 67
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 62,
        "to": 61
      },
      {
        "from": 26,
        "to": 7
      },
      {
        "from": 89,
        "to": 17
      },
      {
        "from": 5,
        "to": 14
      },
      {
        "from": 17,
        "to": 53
      },
      {
        "from": 25,
        "to": 43
      },
      {
        "from": 76,
        "to": 77
      },
      {
        "from": 7,
        "to": 24
      },
      {
        "from": 82,
        "to": 73
      },
      {
        "from": 4,
        "to": 5
      },
      {
        "from": 77,
        "to": 68
      },
      {
        "from": 22,
        "to": 58
      },
      {
        "from": 69,
        "to": 62
      },
      {
        "from": 58,
        "to": 22
      },
      {
        "from": 46,
        "to": 47
      },
      {
        "from": 28,
        "to": 27
      },
      {
        "from": 67,
        "to": 70
      },
      {
        "from": 27,
        "to": 36
      },
      {
        "from": 62,
        "to": 79
      },
      {
        "from": 36,
        "to": 45
      },
      {
        "from": 57,
        "to": 48
      },
      {
        "from": 13,
        "to": 4
      },
      {
        "from": 59,
        "to": 50
      },
      {
        "from": 41,
        "to": 36
      },
      {
        "from": 60,
        "to": 51
      },
      {
        "from": 9,
        "to": 13
      },
      {
        "from": 53,
        "to": 8
      },
      {
        "from": 45,
        "to": 46
      },
      {
        "from": 73,
        "to": 46
      },
      {
        "from": 33,
        "to": 42
      },
      {
        "from": 8,
        "to": 6
      },
      {
        "from": 42,
        "to": 51
      },
      {
        "from": 70,
        "to": 52
      },
      {
        "from": 51,
        "to": 52
      },
      {
        "from": 6,
        "to": 24
      },
      {
        "from": 14,
        "to": 23
      },
      {
        "from": 24,
        "to": 78
      },
      {
        "from": 36,
        "to": 18
      },
      {
        "from": 46,
        "to": 55
      },
      {
        "from": 52,
        "to": 61
      },
      {
        "from": 55,
        "to": 61
      },
      {
        "from": 43,
        "to": 16
      },
      {
        "from": 61,
        "to": 34
      },
      {
        "from": 16,
        "to": 9
      },
      {
        "from": 34,
        "to": 43
      },
      {
        "from": 13,
        "to": 10
      },
      {
        "from": 79,
        "to": 62
      },
      {
        "from": 18,
        "to": 27
      },
      {
        "from": 43,
        "to": 61
      },
      {
        "from": 27,
        "to": 36
      },
      {
        "from": 66,
        "to": 71
      },
      {
        "from": 4,
        "to": 3
      },
      {
        "from": 71,
        "to": 8
      },
      {
        "from": 3,
        "to": 13
      },
      {
        "from": 8,
        "to": 2
      },
      {
        "from": 9,
        "to": 63
      },
      {
        "from": 68,
        "to": 77
      },
      {
        "from": 10,
        "to": 73
      },
      {
        "from": 84,
        "to": 76
      },
      {
        "from": 29,
        "to": 30
      },
      {
        "from": 78,
        "to": 15
      },
      {
        "from": 13,
        "to": 21
      },
      {
        "from": 47,
        "to": 38
      },
      {
        "from": 63,
        "to": 71
      },
      {
        "from": 2,
        "to": 6
      },
      {
        "from": 36,
        "to": 38
      },
      {
        "from": 6,
        "to": 24
      },
      {
        "from": 38,
        "to": 65
      },
      {
        "from": 24,
        "to": 6
      },
      {
        "from": 65,
        "to": 83
      },
      {
        "from": 48,
        "to": 39
      },
      {
        "from": 20,
        "to": 39
      },
      {
        "from": 50,
        "to": 41
      },
      {
        "from": 5,
        "to": 4
      },
      {
        "from": 41,
        "to": 40
      },
      {
        "from": 31,
        "to": 40
      },
      {
        "from": 62,
        "to": 43
      },
      {
        "from": 39,
        "to": 56
      },
      {
        "from": 43,
        "to": 32
      },
      {
        "from": 30,
        "to": 31
      },
      {
        "from": 61,
        "to": 57
      },
      {
        "from": 56,
        "to": 39
      },
      {
        "from": 32,
        "to": 43
      },
      {
        "from": 4,
        "to": 13
      },
      {
        "from": 57,
        "to": 54
      },
      {
        "from": 13,
        "to": 3
      },
      {
        "from": 76,
        "to": 75
      },
      {
        "from": 73,
        "to": 75
      },
      {
        "from": 77,
        "to": 68
      }
    ],
    "tier": 1,
    "source": "generated"
  },
  {
    "id": "janggi-t1-2",
    "sideToMove": 2,
    "solution": [
      {
        "from": 87,
        "to": 84
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 76,
        "to": 85
      },
      {
        "from": 13,
        "to": 4
      },
      {
        "from": 80,
        "to": 77
      },
      {
        "from": 44,
        "to": 62
      },
      {
        "from": 45,
        "to": 53
      },
      {
        "from": 62,
        "to": 53
      },
      {
        "from": 64,
        "to": 37
      },
      {
        "from": 5,
        "to": 13
      },
      {
        "from": 77,
        "to": 41
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 37,
        "to": 73
      },
      {
        "from": 28,
        "to": 27
      },
      {
        "from": 84,
        "to": 75
      },
      {
        "from": 19,
        "to": 64
      },
      {
        "from": 55,
        "to": 54
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 3,
        "to": 12
      },
      {
        "from": 85,
        "to": 76
      },
      {
        "from": 34,
        "to": 35
      },
      {
        "from": 76,
        "to": 85
      },
      {
        "from": 25,
        "to": 19
      },
      {
        "from": 60,
        "to": 61
      },
      {
        "from": 7,
        "to": 26
      },
      {
        "from": 73,
        "to": 78
      },
      {
        "from": 9,
        "to": 45
      },
      {
        "from": 55,
        "to": 46
      },
      {
        "from": 45,
        "to": 46
      },
      {
        "from": 82,
        "to": 63
      },
      {
        "from": 46,
        "to": 45
      },
      {
        "from": 63,
        "to": 82
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 75,
        "to": 76
      },
      {
        "from": 26,
        "to": 7
      },
      {
        "from": 41,
        "to": 39
      },
      {
        "from": 29,
        "to": 30
      },
      {
        "from": 39,
        "to": 41
      },
      {
        "from": 53,
        "to": 17
      },
      {
        "from": 56,
        "to": 57
      },
      {
        "from": 17,
        "to": 53
      },
      {
        "from": 57,
        "to": 56
      },
      {
        "from": 19,
        "to": 21
      },
      {
        "from": 56,
        "to": 55
      },
      {
        "from": 28,
        "to": 29
      },
      {
        "from": 55,
        "to": 56
      },
      {
        "from": 13,
        "to": 22
      },
      {
        "from": 78,
        "to": 74
      },
      {
        "from": 31,
        "to": 40
      },
      {
        "from": 74,
        "to": 47
      },
      {
        "from": 40,
        "to": 41
      },
      {
        "from": 47,
        "to": 20
      },
      {
        "from": 33,
        "to": 42
      },
      {
        "from": 70,
        "to": 34
      },
      {
        "from": 29,
        "to": 38
      },
      {
        "from": 34,
        "to": 70
      },
      {
        "from": 7,
        "to": 24
      },
      {
        "from": 58,
        "to": 59
      },
      {
        "from": 24,
        "to": 13
      },
      {
        "from": 59,
        "to": 58
      },
      {
        "from": 38,
        "to": 37
      },
      {
        "from": 20,
        "to": 74
      },
      {
        "from": 2,
        "to": 27
      },
      {
        "from": 56,
        "to": 55
      },
      {
        "from": 21,
        "to": 24
      },
      {
        "from": 55,
        "to": 56
      },
      {
        "from": 24,
        "to": 69
      },
      {
        "from": 70,
        "to": 7
      },
      {
        "from": 6,
        "to": 31
      },
      {
        "from": 56,
        "to": 55
      },
      {
        "from": 69,
        "to": 6
      },
      {
        "from": 74,
        "to": 78
      },
      {
        "from": 37,
        "to": 38
      },
      {
        "from": 7,
        "to": 70
      },
      {
        "from": 53,
        "to": 52
      },
      {
        "from": 61,
        "to": 52
      },
      {
        "from": 45,
        "to": 52
      },
      {
        "from": 55,
        "to": 54
      },
      {
        "from": 52,
        "to": 70
      },
      {
        "from": 54,
        "to": 45
      },
      {
        "from": 64,
        "to": 71
      },
      {
        "from": 45,
        "to": 36
      },
      {
        "from": 31,
        "to": 60
      },
      {
        "from": 76,
        "to": 77
      },
      {
        "from": 70,
        "to": 67
      },
      {
        "from": 78,
        "to": 76
      },
      {
        "from": 27,
        "to": 2
      },
      {
        "from": 36,
        "to": 27
      },
      {
        "from": 2,
        "to": 27
      },
      {
        "from": 58,
        "to": 49
      },
      {
        "from": 67,
        "to": 49
      },
      {
        "from": 83,
        "to": 58
      },
      {
        "from": 27,
        "to": 56
      },
      {
        "from": 85,
        "to": 84
      },
      {
        "from": 49,
        "to": 48
      },
      {
        "from": 82,
        "to": 75
      },
      {
        "from": 48,
        "to": 75
      },
      {
        "from": 84,
        "to": 85
      },
      {
        "from": 30,
        "to": 39
      },
      {
        "from": 76,
        "to": 22
      },
      {
        "from": 4,
        "to": 5
      },
      {
        "from": 22,
        "to": 67
      },
      {
        "from": 75,
        "to": 77
      },
      {
        "from": 85,
        "to": 84
      },
      {
        "from": 77,
        "to": 86
      },
      {
        "from": 84,
        "to": 75
      },
      {
        "from": 86,
        "to": 87
      },
      {
        "from": 75,
        "to": 66
      }
    ],
    "tier": 1,
    "source": "generated"
  },
  {
    "id": "janggi-t1-3",
    "sideToMove": 1,
    "solution": [
      {
        "from": 21,
        "to": 5
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 44,
        "to": 43
      },
      {
        "from": 76,
        "to": 67
      },
      {
        "from": 43,
        "to": 70
      },
      {
        "from": 62,
        "to": 61
      },
      {
        "from": 31,
        "to": 40
      },
      {
        "from": 80,
        "to": 17
      },
      {
        "from": 13,
        "to": 4
      },
      {
        "from": 45,
        "to": 48
      },
      {
        "from": 29,
        "to": 30
      },
      {
        "from": 48,
        "to": 30
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 64,
        "to": 28
      },
      {
        "from": 70,
        "to": 69
      },
      {
        "from": 67,
        "to": 76
      },
      {
        "from": 0,
        "to": 72
      },
      {
        "from": 76,
        "to": 85
      },
      {
        "from": 69,
        "to": 67
      },
      {
        "from": 84,
        "to": 76
      },
      {
        "from": 67,
        "to": 69
      },
      {
        "from": 76,
        "to": 84
      },
      {
        "from": 69,
        "to": 67
      },
      {
        "from": 84,
        "to": 76
      },
      {
        "from": 67,
        "to": 69
      },
      {
        "from": 76,
        "to": 84
      },
      {
        "from": 69,
        "to": 67
      },
      {
        "from": 84,
        "to": 76
      },
      {
        "from": 67,
        "to": 69
      },
      {
        "from": 76,
        "to": 84
      },
      {
        "from": 69,
        "to": 67
      },
      {
        "from": 84,
        "to": 76
      },
      {
        "from": 67,
        "to": 69
      },
      {
        "from": 76,
        "to": 84
      },
      {
        "from": 69,
        "to": 67
      },
      {
        "from": 84,
        "to": 76
      },
      {
        "from": 67,
        "to": 69
      },
      {
        "from": 76,
        "to": 84
      },
      {
        "from": 69,
        "to": 67
      },
      {
        "from": 84,
        "to": 76
      },
      {
        "from": 20,
        "to": 39
      },
      {
        "from": 76,
        "to": 67
      },
      {
        "from": 39,
        "to": 28
      },
      {
        "from": 30,
        "to": 28
      },
      {
        "from": 19,
        "to": 55
      },
      {
        "from": 56,
        "to": 55
      },
      {
        "from": 7,
        "to": 24
      },
      {
        "from": 61,
        "to": 62
      },
      {
        "from": 34,
        "to": 43
      },
      {
        "from": 28,
        "to": 33
      },
      {
        "from": 24,
        "to": 7
      },
      {
        "from": 33,
        "to": 6
      },
      {
        "from": 3,
        "to": 13
      },
      {
        "from": 82,
        "to": 65
      },
      {
        "from": 72,
        "to": 45
      },
      {
        "from": 6,
        "to": 7
      },
      {
        "from": 25,
        "to": 70
      },
      {
        "from": 7,
        "to": 43
      },
      {
        "from": 70,
        "to": 65
      },
      {
        "from": 43,
        "to": 40
      },
      {
        "from": 65,
        "to": 69
      },
      {
        "from": 40,
        "to": 44
      },
      {
        "from": 13,
        "to": 22
      },
      {
        "from": 17,
        "to": 16
      },
      {
        "from": 22,
        "to": 23
      },
      {
        "from": 60,
        "to": 59
      },
      {
        "from": 69,
        "to": 64
      },
      {
        "from": 55,
        "to": 56
      },
      {
        "from": 45,
        "to": 27
      },
      {
        "from": 67,
        "to": 76
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 44,
        "to": 39
      },
      {
        "from": 64,
        "to": 19
      },
      {
        "from": 16,
        "to": 70
      },
      {
        "from": 19,
        "to": 26
      },
      {
        "from": 62,
        "to": 53
      },
      {
        "from": 26,
        "to": 20
      },
      {
        "from": 39,
        "to": 21
      },
      {
        "from": 20,
        "to": 83
      },
      {
        "from": 86,
        "to": 77
      },
      {
        "from": 83,
        "to": 87
      },
      {
        "from": 56,
        "to": 47
      },
      {
        "from": 28,
        "to": 82
      },
      {
        "from": 76,
        "to": 84
      },
      {
        "from": 23,
        "to": 14
      },
      {
        "from": 21,
        "to": 22
      },
      {
        "from": 5,
        "to": 13
      },
      {
        "from": 70,
        "to": 7
      },
      {
        "from": 14,
        "to": 5
      },
      {
        "from": 7,
        "to": 25
      },
      {
        "from": 13,
        "to": 22
      },
      {
        "from": 25,
        "to": 24
      },
      {
        "from": 87,
        "to": 84
      },
      {
        "from": 24,
        "to": 22
      },
      {
        "from": 4,
        "to": 3
      },
      {
        "from": 22,
        "to": 21
      },
      {
        "from": 84,
        "to": 12
      },
      {
        "from": 85,
        "to": 76
      },
      {
        "from": 82,
        "to": 73
      },
      {
        "from": 76,
        "to": 68
      },
      {
        "from": 73,
        "to": 64
      },
      {
        "from": 68,
        "to": 76
      },
      {
        "from": 64,
        "to": 73
      },
      {
        "from": 76,
        "to": 68
      },
      {
        "from": 73,
        "to": 75
      }
    ],
    "tier": 1,
    "source": "generated"
  },
  {
    "id": "janggi-t2-4",
    "sideToMove": 2,
    "solution": [
      {
        "from": 51,
        "to": 87
      },
      {
        "from": 76,
        "to": 86
      },
      {
        "from": 87,
        "to": 86
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 76,
        "to": 85
      },
      {
        "from": 13,
        "to": 4
      },
      {
        "from": 80,
        "to": 77
      },
      {
        "from": 44,
        "to": 62
      },
      {
        "from": 45,
        "to": 48
      },
      {
        "from": 62,
        "to": 60
      },
      {
        "from": 69,
        "to": 88
      },
      {
        "from": 60,
        "to": 87
      },
      {
        "from": 88,
        "to": 71
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 64,
        "to": 46
      },
      {
        "from": 33,
        "to": 32
      },
      {
        "from": 46,
        "to": 49
      },
      {
        "from": 31,
        "to": 30
      },
      {
        "from": 49,
        "to": 67
      },
      {
        "from": 19,
        "to": 22
      },
      {
        "from": 77,
        "to": 32
      },
      {
        "from": 5,
        "to": 13
      },
      {
        "from": 32,
        "to": 34
      },
      {
        "from": 13,
        "to": 23
      },
      {
        "from": 34,
        "to": 25
      },
      {
        "from": 9,
        "to": 36
      },
      {
        "from": 70,
        "to": 7
      },
      {
        "from": 4,
        "to": 13
      },
      {
        "from": 48,
        "to": 49
      },
      {
        "from": 30,
        "to": 31
      },
      {
        "from": 25,
        "to": 16
      },
      {
        "from": 23,
        "to": 14
      },
      {
        "from": 49,
        "to": 50
      },
      {
        "from": 6,
        "to": 35
      },
      {
        "from": 50,
        "to": 77
      },
      {
        "from": 87,
        "to": 51
      },
      {
        "from": 7,
        "to": 2
      },
      {
        "from": 3,
        "to": 12
      },
      {
        "from": 58,
        "to": 57
      },
      {
        "from": 31,
        "to": 32
      },
      {
        "from": 77,
        "to": 32
      },
      {
        "from": 22,
        "to": 19
      },
      {
        "from": 32,
        "to": 35
      },
      {
        "from": 36,
        "to": 41
      },
      {
        "from": 57,
        "to": 58
      },
      {
        "from": 19,
        "to": 22
      },
      {
        "from": 86,
        "to": 76
      }
    ],
    "tier": 2,
    "source": "generated"
  },
  {
    "id": "janggi-t1-5",
    "sideToMove": 1,
    "solution": [
      {
        "from": 72,
        "to": 9
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 3,
        "to": 4
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 76,
        "to": 67
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 44,
        "to": 39
      },
      {
        "from": 84,
        "to": 85
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 80,
        "to": 77
      },
      {
        "from": 33,
        "to": 32
      },
      {
        "from": 60,
        "to": 61
      },
      {
        "from": 25,
        "to": 43
      },
      {
        "from": 62,
        "to": 53
      },
      {
        "from": 13,
        "to": 3
      },
      {
        "from": 58,
        "to": 49
      },
      {
        "from": 9,
        "to": 15
      },
      {
        "from": 61,
        "to": 60
      },
      {
        "from": 15,
        "to": 60
      },
      {
        "from": 45,
        "to": 27
      },
      {
        "from": 60,
        "to": 15
      },
      {
        "from": 27,
        "to": 29
      },
      {
        "from": 20,
        "to": 1
      },
      {
        "from": 29,
        "to": 2
      },
      {
        "from": 3,
        "to": 13
      },
      {
        "from": 2,
        "to": 1
      },
      {
        "from": 13,
        "to": 22
      },
      {
        "from": 1,
        "to": 19
      },
      {
        "from": 22,
        "to": 13
      },
      {
        "from": 19,
        "to": 10
      },
      {
        "from": 13,
        "to": 22
      },
      {
        "from": 10,
        "to": 15
      },
      {
        "from": 43,
        "to": 25
      },
      {
        "from": 15,
        "to": 6
      },
      {
        "from": 7,
        "to": 26
      },
      {
        "from": 56,
        "to": 47
      },
      {
        "from": 22,
        "to": 23
      },
      {
        "from": 6,
        "to": 24
      },
      {
        "from": 23,
        "to": 14
      },
      {
        "from": 69,
        "to": 58
      },
      {
        "from": 25,
        "to": 61
      },
      {
        "from": 24,
        "to": 26
      },
      {
        "from": 61,
        "to": 55
      },
      {
        "from": 70,
        "to": 16
      },
      {
        "from": 34,
        "to": 33
      },
      {
        "from": 53,
        "to": 52
      },
      {
        "from": 55,
        "to": 61
      },
      {
        "from": 52,
        "to": 51
      },
      {
        "from": 61,
        "to": 56
      },
      {
        "from": 47,
        "to": 46
      },
      {
        "from": 56,
        "to": 60
      },
      {
        "from": 58,
        "to": 47
      },
      {
        "from": 14,
        "to": 13
      },
      {
        "from": 77,
        "to": 72
      },
      {
        "from": 13,
        "to": 3
      },
      {
        "from": 26,
        "to": 23
      },
      {
        "from": 3,
        "to": 12
      }
    ],
    "tier": 1,
    "source": "generated"
  },
  {
    "id": "janggi-t1-6",
    "sideToMove": 2,
    "solution": [
      {
        "from": 67,
        "to": 66
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 45,
        "to": 63
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 63,
        "to": 45
      },
      {
        "from": 13,
        "to": 4
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 9,
        "to": 12
      },
      {
        "from": 45,
        "to": 27
      },
      {
        "from": 7,
        "to": 24
      },
      {
        "from": 27,
        "to": 29
      },
      {
        "from": 20,
        "to": 1
      },
      {
        "from": 58,
        "to": 49
      },
      {
        "from": 44,
        "to": 36
      },
      {
        "from": 84,
        "to": 85
      },
      {
        "from": 36,
        "to": 72
      },
      {
        "from": 76,
        "to": 67
      },
      {
        "from": 72,
        "to": 80
      },
      {
        "from": 29,
        "to": 2
      },
      {
        "from": 80,
        "to": 62
      },
      {
        "from": 2,
        "to": 1
      },
      {
        "from": 62,
        "to": 60
      },
      {
        "from": 69,
        "to": 88
      },
      {
        "from": 60,
        "to": 87
      },
      {
        "from": 88,
        "to": 71
      },
      {
        "from": 87,
        "to": 78
      },
      {
        "from": 1,
        "to": 2
      },
      {
        "from": 78,
        "to": 72
      },
      {
        "from": 64,
        "to": 46
      },
      {
        "from": 31,
        "to": 40
      },
      {
        "from": 49,
        "to": 40
      },
      {
        "from": 25,
        "to": 22
      },
      {
        "from": 83,
        "to": 58
      },
      {
        "from": 22,
        "to": 58
      },
      {
        "from": 40,
        "to": 39
      },
      {
        "from": 12,
        "to": 39
      },
      {
        "from": 67,
        "to": 68
      },
      {
        "from": 39,
        "to": 41
      },
      {
        "from": 68,
        "to": 67
      },
      {
        "from": 19,
        "to": 25
      },
      {
        "from": 67,
        "to": 66
      },
      {
        "from": 41,
        "to": 68
      },
      {
        "from": 70,
        "to": 67
      },
      {
        "from": 68,
        "to": 71
      },
      {
        "from": 2,
        "to": 47
      },
      {
        "from": 72,
        "to": 36
      },
      {
        "from": 47,
        "to": 49
      },
      {
        "from": 6,
        "to": 31
      },
      {
        "from": 49,
        "to": 58
      },
      {
        "from": 36,
        "to": 39
      },
      {
        "from": 56,
        "to": 57
      },
      {
        "from": 39,
        "to": 38
      },
      {
        "from": 58,
        "to": 31
      },
      {
        "from": 3,
        "to": 13
      },
      {
        "from": 31,
        "to": 33
      },
      {
        "from": 13,
        "to": 12
      },
      {
        "from": 33,
        "to": 31
      },
      {
        "from": 4,
        "to": 3
      },
      {
        "from": 31,
        "to": 34
      },
      {
        "from": 25,
        "to": 21
      },
      {
        "from": 57,
        "to": 58
      },
      {
        "from": 38,
        "to": 20
      },
      {
        "from": 58,
        "to": 49
      },
      {
        "from": 20,
        "to": 38
      },
      {
        "from": 82,
        "to": 65
      },
      {
        "from": 38,
        "to": 65
      },
      {
        "from": 66,
        "to": 76
      },
      {
        "from": 65,
        "to": 67
      },
      {
        "from": 76,
        "to": 84
      }
    ],
    "tier": 1,
    "source": "generated"
  },
  {
    "id": "janggi-t1-7",
    "sideToMove": 2,
    "solution": [
      {
        "from": 81,
        "to": 84
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 82,
        "to": 63
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 63,
        "to": 82
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 81,
        "to": 27
      },
      {
        "from": 9,
        "to": 27
      },
      {
        "from": 56,
        "to": 47
      },
      {
        "from": 27,
        "to": 72
      },
      {
        "from": 76,
        "to": 85
      },
      {
        "from": 25,
        "to": 52
      },
      {
        "from": 64,
        "to": 46
      },
      {
        "from": 13,
        "to": 21
      },
      {
        "from": 62,
        "to": 53
      },
      {
        "from": 44,
        "to": 17
      },
      {
        "from": 89,
        "to": 62
      },
      {
        "from": 52,
        "to": 25
      },
      {
        "from": 60,
        "to": 51
      },
      {
        "from": 72,
        "to": 81
      },
      {
        "from": 82,
        "to": 65
      },
      {
        "from": 81,
        "to": 83
      },
      {
        "from": 65,
        "to": 76
      },
      {
        "from": 83,
        "to": 47
      },
      {
        "from": 46,
        "to": 73
      },
      {
        "from": 47,
        "to": 51
      },
      {
        "from": 69,
        "to": 88
      },
      {
        "from": 19,
        "to": 64
      },
      {
        "from": 84,
        "to": 75
      },
      {
        "from": 17,
        "to": 9
      },
      {
        "from": 53,
        "to": 52
      },
      {
        "from": 25,
        "to": 52
      },
      {
        "from": 55,
        "to": 54
      },
      {
        "from": 9,
        "to": 54
      },
      {
        "from": 62,
        "to": 44
      },
      {
        "from": 54,
        "to": 81
      },
      {
        "from": 75,
        "to": 84
      },
      {
        "from": 51,
        "to": 46
      },
      {
        "from": 73,
        "to": 79
      },
      {
        "from": 81,
        "to": 9
      },
      {
        "from": 44,
        "to": 39
      },
      {
        "from": 29,
        "to": 30
      },
      {
        "from": 39,
        "to": 41
      },
      {
        "from": 5,
        "to": 4
      },
      {
        "from": 41,
        "to": 23
      },
      {
        "from": 21,
        "to": 12
      },
      {
        "from": 23,
        "to": 20
      },
      {
        "from": 2,
        "to": 27
      },
      {
        "from": 79,
        "to": 75
      },
      {
        "from": 27,
        "to": 48
      },
      {
        "from": 58,
        "to": 49
      },
      {
        "from": 46,
        "to": 55
      },
      {
        "from": 49,
        "to": 48
      },
      {
        "from": 9,
        "to": 36
      },
      {
        "from": 20,
        "to": 11
      },
      {
        "from": 12,
        "to": 21
      },
      {
        "from": 11,
        "to": 20
      },
      {
        "from": 21,
        "to": 13
      },
      {
        "from": 76,
        "to": 59
      },
      {
        "from": 55,
        "to": 59
      },
      {
        "from": 86,
        "to": 76
      },
      {
        "from": 59,
        "to": 57
      },
      {
        "from": 20,
        "to": 11
      },
      {
        "from": 13,
        "to": 22
      },
      {
        "from": 11,
        "to": 20
      },
      {
        "from": 6,
        "to": 21
      },
      {
        "from": 75,
        "to": 78
      },
      {
        "from": 57,
        "to": 48
      },
      {
        "from": 20,
        "to": 11
      },
      {
        "from": 48,
        "to": 50
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 52,
        "to": 49
      },
      {
        "from": 70,
        "to": 67
      },
      {
        "from": 50,
        "to": 59
      },
      {
        "from": 11,
        "to": 17
      },
      {
        "from": 33,
        "to": 32
      },
      {
        "from": 17,
        "to": 11
      },
      {
        "from": 59,
        "to": 55
      },
      {
        "from": 76,
        "to": 77
      },
      {
        "from": 22,
        "to": 23
      },
      {
        "from": 67,
        "to": 70
      },
      {
        "from": 49,
        "to": 22
      },
      {
        "from": 85,
        "to": 86
      },
      {
        "from": 34,
        "to": 35
      },
      {
        "from": 84,
        "to": 76
      },
      {
        "from": 35,
        "to": 44
      },
      {
        "from": 76,
        "to": 84
      },
      {
        "from": 44,
        "to": 53
      },
      {
        "from": 78,
        "to": 72
      },
      {
        "from": 36,
        "to": 72
      },
      {
        "from": 69,
        "to": 52
      },
      {
        "from": 72,
        "to": 81
      },
      {
        "from": 70,
        "to": 7
      }
    ],
    "tier": 1,
    "source": "generated"
  },
  {
    "id": "janggi-t1-8",
    "sideToMove": 1,
    "solution": [
      {
        "from": 23,
        "to": 13
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 76,
        "to": 85
      },
      {
        "from": 13,
        "to": 4
      },
      {
        "from": 80,
        "to": 77
      },
      {
        "from": 44,
        "to": 62
      },
      {
        "from": 45,
        "to": 48
      },
      {
        "from": 62,
        "to": 60
      },
      {
        "from": 69,
        "to": 88
      },
      {
        "from": 60,
        "to": 87
      },
      {
        "from": 88,
        "to": 71
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 64,
        "to": 46
      },
      {
        "from": 33,
        "to": 32
      },
      {
        "from": 46,
        "to": 49
      },
      {
        "from": 31,
        "to": 30
      },
      {
        "from": 49,
        "to": 67
      },
      {
        "from": 19,
        "to": 22
      },
      {
        "from": 77,
        "to": 32
      },
      {
        "from": 5,
        "to": 13
      },
      {
        "from": 32,
        "to": 34
      },
      {
        "from": 13,
        "to": 23
      },
      {
        "from": 34,
        "to": 25
      },
      {
        "from": 7,
        "to": 26
      },
      {
        "from": 25,
        "to": 26
      },
      {
        "from": 87,
        "to": 78
      },
      {
        "from": 26,
        "to": 23
      },
      {
        "from": 30,
        "to": 39
      },
      {
        "from": 48,
        "to": 45
      },
      {
        "from": 9,
        "to": 45
      },
      {
        "from": 23,
        "to": 22
      },
      {
        "from": 3,
        "to": 13
      },
      {
        "from": 22,
        "to": 20
      },
      {
        "from": 39,
        "to": 40
      },
      {
        "from": 20,
        "to": 2
      },
      {
        "from": 13,
        "to": 3
      },
      {
        "from": 58,
        "to": 59
      },
      {
        "from": 40,
        "to": 39
      },
      {
        "from": 59,
        "to": 58
      },
      {
        "from": 6,
        "to": 31
      },
      {
        "from": 67,
        "to": 31
      },
      {
        "from": 29,
        "to": 38
      },
      {
        "from": 2,
        "to": 20
      },
      {
        "from": 38,
        "to": 37
      },
      {
        "from": 20,
        "to": 23
      },
      {
        "from": 3,
        "to": 12
      },
      {
        "from": 31,
        "to": 67
      },
      {
        "from": 39,
        "to": 40
      },
      {
        "from": 67,
        "to": 40
      },
      {
        "from": 37,
        "to": 38
      },
      {
        "from": 40,
        "to": 67
      },
      {
        "from": 12,
        "to": 13
      }
    ],
    "tier": 1,
    "source": "generated"
  },
  {
    "id": "janggi-t1-9",
    "sideToMove": 1,
    "solution": [
      {
        "from": 58,
        "to": 29
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 45,
        "to": 81
      },
      {
        "from": 13,
        "to": 4
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 9,
        "to": 12
      },
      {
        "from": 45,
        "to": 27
      },
      {
        "from": 7,
        "to": 24
      },
      {
        "from": 27,
        "to": 29
      },
      {
        "from": 20,
        "to": 1
      },
      {
        "from": 29,
        "to": 2
      },
      {
        "from": 1,
        "to": 18
      },
      {
        "from": 56,
        "to": 57
      },
      {
        "from": 44,
        "to": 41
      },
      {
        "from": 58,
        "to": 59
      },
      {
        "from": 12,
        "to": 17
      },
      {
        "from": 70,
        "to": 67
      },
      {
        "from": 31,
        "to": 30
      },
      {
        "from": 83,
        "to": 58
      },
      {
        "from": 6,
        "to": 31
      }
    ],
    "tier": 1,
    "source": "generated"
  },
  {
    "id": "janggi-t1-10",
    "sideToMove": 1,
    "solution": [
      {
        "from": 22,
        "to": 23
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 76,
        "to": 85
      },
      {
        "from": 13,
        "to": 4
      },
      {
        "from": 80,
        "to": 77
      },
      {
        "from": 44,
        "to": 62
      },
      {
        "from": 45,
        "to": 48
      },
      {
        "from": 62,
        "to": 60
      },
      {
        "from": 69,
        "to": 88
      },
      {
        "from": 60,
        "to": 87
      },
      {
        "from": 88,
        "to": 71
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 64,
        "to": 46
      },
      {
        "from": 33,
        "to": 32
      },
      {
        "from": 46,
        "to": 49
      },
      {
        "from": 31,
        "to": 30
      },
      {
        "from": 49,
        "to": 67
      },
      {
        "from": 19,
        "to": 22
      },
      {
        "from": 77,
        "to": 32
      },
      {
        "from": 5,
        "to": 13
      },
      {
        "from": 32,
        "to": 34
      },
      {
        "from": 13,
        "to": 23
      },
      {
        "from": 34,
        "to": 25
      },
      {
        "from": 7,
        "to": 26
      },
      {
        "from": 25,
        "to": 26
      },
      {
        "from": 87,
        "to": 78
      },
      {
        "from": 26,
        "to": 23
      },
      {
        "from": 30,
        "to": 39
      },
      {
        "from": 23,
        "to": 22
      },
      {
        "from": 4,
        "to": 5
      },
      {
        "from": 48,
        "to": 39
      },
      {
        "from": 20,
        "to": 1
      },
      {
        "from": 39,
        "to": 3
      },
      {
        "from": 5,
        "to": 14
      }
    ],
    "tier": 1,
    "source": "generated"
  },
  {
    "id": "janggi-t1-11",
    "sideToMove": 2,
    "solution": [
      {
        "from": 80,
        "to": 71
      }
    ],
    "setupMoves": [
      {
        "from": 84,
        "to": 75
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 62,
        "to": 61
      },
      {
        "from": 0,
        "to": 36
      },
      {
        "from": 89,
        "to": 53
      },
      {
        "from": 7,
        "to": 24
      },
      {
        "from": 82,
        "to": 65
      },
      {
        "from": 8,
        "to": 17
      },
      {
        "from": 53,
        "to": 50
      },
      {
        "from": 5,
        "to": 4
      },
      {
        "from": 70,
        "to": 52
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 52,
        "to": 49
      },
      {
        "from": 25,
        "to": 22
      },
      {
        "from": 56,
        "to": 47
      },
      {
        "from": 36,
        "to": 43
      },
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 19,
        "to": 55
      },
      {
        "from": 60,
        "to": 59
      },
      {
        "from": 43,
        "to": 61
      },
      {
        "from": 81,
        "to": 9
      },
      {
        "from": 13,
        "to": 21
      },
      {
        "from": 58,
        "to": 57
      },
      {
        "from": 55,
        "to": 10
      },
      {
        "from": 64,
        "to": 66
      },
      {
        "from": 29,
        "to": 30
      },
      {
        "from": 57,
        "to": 56
      },
      {
        "from": 30,
        "to": 29
      },
      {
        "from": 9,
        "to": 81
      },
      {
        "from": 61,
        "to": 88
      },
      {
        "from": 66,
        "to": 84
      },
      {
        "from": 29,
        "to": 30
      },
      {
        "from": 84,
        "to": 57
      },
      {
        "from": 30,
        "to": 29
      },
      {
        "from": 47,
        "to": 48
      },
      {
        "from": 21,
        "to": 13
      },
      {
        "from": 81,
        "to": 36
      },
      {
        "from": 17,
        "to": 80
      },
      {
        "from": 86,
        "to": 77
      },
      {
        "from": 88,
        "to": 87
      },
      {
        "from": 59,
        "to": 58
      },
      {
        "from": 87,
        "to": 83
      },
      {
        "from": 65,
        "to": 72
      },
      {
        "from": 10,
        "to": 73
      },
      {
        "from": 76,
        "to": 68
      }
    ],
    "tier": 1,
    "source": "generated"
  },
  {
    "id": "janggi-t2-12",
    "sideToMove": 2,
    "solution": [
      {
        "from": 19,
        "to": 82
      },
      {
        "from": 76,
        "to": 84
      },
      {
        "from": 39,
        "to": 84
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 44,
        "to": 36
      },
      {
        "from": 45,
        "to": 36
      },
      {
        "from": 27,
        "to": 36
      },
      {
        "from": 80,
        "to": 77
      },
      {
        "from": 5,
        "to": 4
      },
      {
        "from": 76,
        "to": 85
      },
      {
        "from": 36,
        "to": 45
      },
      {
        "from": 56,
        "to": 47
      },
      {
        "from": 0,
        "to": 36
      },
      {
        "from": 58,
        "to": 49
      },
      {
        "from": 36,
        "to": 39
      },
      {
        "from": 47,
        "to": 38
      },
      {
        "from": 29,
        "to": 38
      },
      {
        "from": 84,
        "to": 76
      },
      {
        "from": 38,
        "to": 47
      },
      {
        "from": 60,
        "to": 51
      },
      {
        "from": 7,
        "to": 24
      },
      {
        "from": 62,
        "to": 53
      },
      {
        "from": 3,
        "to": 12
      },
      {
        "from": 77,
        "to": 59
      },
      {
        "from": 12,
        "to": 3
      },
      {
        "from": 64,
        "to": 28
      },
      {
        "from": 33,
        "to": 32
      },
      {
        "from": 82,
        "to": 63
      },
      {
        "from": 4,
        "to": 5
      },
      {
        "from": 51,
        "to": 42
      },
      {
        "from": 39,
        "to": 42
      },
      {
        "from": 69,
        "to": 88
      },
      {
        "from": 42,
        "to": 87
      },
      {
        "from": 88,
        "to": 71
      },
      {
        "from": 87,
        "to": 42
      },
      {
        "from": 59,
        "to": 68
      },
      {
        "from": 42,
        "to": 39
      },
      {
        "from": 68,
        "to": 69
      },
      {
        "from": 32,
        "to": 33
      },
      {
        "from": 63,
        "to": 74
      },
      {
        "from": 33,
        "to": 42
      },
      {
        "from": 28,
        "to": 34
      }
    ],
    "tier": 2,
    "source": "generated"
  },
  {
    "id": "janggi-t2-13",
    "sideToMove": 1,
    "solution": [
      {
        "from": 63,
        "to": 68
      },
      {
        "from": 42,
        "to": 41
      },
      {
        "from": 68,
        "to": 41
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 45
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 45,
        "to": 36
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 36,
        "to": 27
      },
      {
        "from": 5,
        "to": 4
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 28,
        "to": 27
      },
      {
        "from": 56,
        "to": 55
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 44,
        "to": 41
      },
      {
        "from": 86,
        "to": 85
      },
      {
        "from": 41,
        "to": 44
      },
      {
        "from": 69,
        "to": 86
      },
      {
        "from": 44,
        "to": 41
      },
      {
        "from": 86,
        "to": 67
      },
      {
        "from": 25,
        "to": 43
      },
      {
        "from": 62,
        "to": 61
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 80,
        "to": 17
      },
      {
        "from": 13,
        "to": 23
      },
      {
        "from": 17,
        "to": 9
      },
      {
        "from": 19,
        "to": 22
      },
      {
        "from": 64,
        "to": 19
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 55,
        "to": 56
      },
      {
        "from": 20,
        "to": 1
      },
      {
        "from": 9,
        "to": 17
      },
      {
        "from": 6,
        "to": 21
      },
      {
        "from": 60,
        "to": 51
      },
      {
        "from": 28,
        "to": 37
      },
      {
        "from": 58,
        "to": 49
      },
      {
        "from": 37,
        "to": 38
      },
      {
        "from": 45,
        "to": 9
      },
      {
        "from": 41,
        "to": 59
      },
      {
        "from": 61,
        "to": 52
      },
      {
        "from": 43,
        "to": 61
      },
      {
        "from": 70,
        "to": 66
      },
      {
        "from": 61,
        "to": 56
      },
      {
        "from": 84,
        "to": 75
      },
      {
        "from": 59,
        "to": 57
      },
      {
        "from": 66,
        "to": 84
      },
      {
        "from": 21,
        "to": 36
      },
      {
        "from": 84,
        "to": 57
      },
      {
        "from": 36,
        "to": 57
      },
      {
        "from": 67,
        "to": 56
      },
      {
        "from": 57,
        "to": 82
      },
      {
        "from": 9,
        "to": 63
      },
      {
        "from": 34,
        "to": 43
      },
      {
        "from": 52,
        "to": 43
      },
      {
        "from": 38,
        "to": 47
      },
      {
        "from": 63,
        "to": 68
      },
      {
        "from": 31,
        "to": 32
      },
      {
        "from": 49,
        "to": 48
      },
      {
        "from": 47,
        "to": 56
      },
      {
        "from": 76,
        "to": 84
      },
      {
        "from": 2,
        "to": 31
      },
      {
        "from": 85,
        "to": 86
      },
      {
        "from": 29,
        "to": 38
      },
      {
        "from": 68,
        "to": 63
      },
      {
        "from": 32,
        "to": 41
      },
      {
        "from": 43,
        "to": 42
      },
      {
        "from": 33,
        "to": 42
      },
      {
        "from": 51,
        "to": 42
      },
      {
        "from": 41,
        "to": 42
      }
    ],
    "tier": 2,
    "source": "generated"
  },
  {
    "id": "janggi-t2-14",
    "sideToMove": 2,
    "solution": [
      {
        "from": 39,
        "to": 48
      },
      {
        "from": 59,
        "to": 57
      },
      {
        "from": 48,
        "to": 57
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 76,
        "to": 85
      },
      {
        "from": 13,
        "to": 4
      },
      {
        "from": 80,
        "to": 77
      },
      {
        "from": 44,
        "to": 62
      },
      {
        "from": 45,
        "to": 48
      },
      {
        "from": 62,
        "to": 60
      },
      {
        "from": 69,
        "to": 88
      },
      {
        "from": 60,
        "to": 87
      },
      {
        "from": 88,
        "to": 71
      },
      {
        "from": 27,
        "to": 28
      },
      {
        "from": 64,
        "to": 46
      },
      {
        "from": 33,
        "to": 32
      },
      {
        "from": 46,
        "to": 49
      },
      {
        "from": 31,
        "to": 30
      },
      {
        "from": 49,
        "to": 67
      },
      {
        "from": 19,
        "to": 22
      },
      {
        "from": 77,
        "to": 32
      },
      {
        "from": 5,
        "to": 13
      },
      {
        "from": 56,
        "to": 47
      },
      {
        "from": 9,
        "to": 36
      },
      {
        "from": 32,
        "to": 31
      },
      {
        "from": 6,
        "to": 31
      },
      {
        "from": 47,
        "to": 38
      },
      {
        "from": 13,
        "to": 5
      },
      {
        "from": 38,
        "to": 29
      },
      {
        "from": 31,
        "to": 60
      },
      {
        "from": 85,
        "to": 76
      },
      {
        "from": 28,
        "to": 29
      },
      {
        "from": 48,
        "to": 50
      },
      {
        "from": 87,
        "to": 78
      },
      {
        "from": 76,
        "to": 66
      },
      {
        "from": 7,
        "to": 24
      },
      {
        "from": 58,
        "to": 49
      },
      {
        "from": 36,
        "to": 39
      },
      {
        "from": 49,
        "to": 48
      },
      {
        "from": 39,
        "to": 36
      },
      {
        "from": 67,
        "to": 64
      },
      {
        "from": 5,
        "to": 13
      },
      {
        "from": 55,
        "to": 46
      },
      {
        "from": 60,
        "to": 31
      },
      {
        "from": 50,
        "to": 59
      },
      {
        "from": 24,
        "to": 7
      },
      {
        "from": 48,
        "to": 47
      },
      {
        "from": 36,
        "to": 39
      },
      {
        "from": 47,
        "to": 48
      }
    ],
    "tier": 2,
    "source": "generated"
  },
  {
    "id": "janggi-t2-15",
    "sideToMove": 2,
    "solution": [
      {
        "from": 18,
        "to": 21
      },
      {
        "from": 55,
        "to": 57
      },
      {
        "from": 21,
        "to": 57
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 64,
        "to": 28
      },
      {
        "from": 29,
        "to": 28
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 45,
        "to": 48
      },
      {
        "from": 3,
        "to": 4
      },
      {
        "from": 62,
        "to": 53
      },
      {
        "from": 44,
        "to": 41
      },
      {
        "from": 55,
        "to": 46
      },
      {
        "from": 25,
        "to": 43
      },
      {
        "from": 58,
        "to": 59
      },
      {
        "from": 19,
        "to": 22
      },
      {
        "from": 87,
        "to": 58
      },
      {
        "from": 22,
        "to": 18
      },
      {
        "from": 48,
        "to": 57
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 56,
        "to": 47
      },
      {
        "from": 7,
        "to": 26
      },
      {
        "from": 53,
        "to": 44
      },
      {
        "from": 43,
        "to": 16
      },
      {
        "from": 89,
        "to": 53
      },
      {
        "from": 27,
        "to": 36
      },
      {
        "from": 70,
        "to": 25
      },
      {
        "from": 31,
        "to": 40
      },
      {
        "from": 47,
        "to": 38
      },
      {
        "from": 16,
        "to": 11
      },
      {
        "from": 53,
        "to": 51
      },
      {
        "from": 41,
        "to": 44
      },
      {
        "from": 58,
        "to": 33
      },
      {
        "from": 34,
        "to": 33
      },
      {
        "from": 51,
        "to": 33
      },
      {
        "from": 18,
        "to": 22
      },
      {
        "from": 59,
        "to": 58
      },
      {
        "from": 40,
        "to": 39
      },
      {
        "from": 58,
        "to": 59
      },
      {
        "from": 20,
        "to": 31
      },
      {
        "from": 59,
        "to": 58
      },
      {
        "from": 31,
        "to": 38
      },
      {
        "from": 58,
        "to": 59
      },
      {
        "from": 38,
        "to": 55
      },
      {
        "from": 57,
        "to": 55
      },
      {
        "from": 9,
        "to": 18
      },
      {
        "from": 33,
        "to": 6
      },
      {
        "from": 39,
        "to": 40
      },
      {
        "from": 76,
        "to": 75
      }
    ],
    "tier": 2,
    "source": "generated"
  },
  {
    "id": "janggi-t2-16",
    "sideToMove": 2,
    "solution": [
      {
        "from": 51,
        "to": 49
      },
      {
        "from": 57,
        "to": 58
      },
      {
        "from": 49,
        "to": 58
      }
    ],
    "setupMoves": [
      {
        "from": 54,
        "to": 55
      },
      {
        "from": 35,
        "to": 34
      },
      {
        "from": 81,
        "to": 45
      },
      {
        "from": 8,
        "to": 44
      },
      {
        "from": 88,
        "to": 69
      },
      {
        "from": 1,
        "to": 20
      },
      {
        "from": 89,
        "to": 80
      },
      {
        "from": 0,
        "to": 9
      },
      {
        "from": 76,
        "to": 85
      },
      {
        "from": 13,
        "to": 4
      },
      {
        "from": 80,
        "to": 77
      },
      {
        "from": 44,
        "to": 62
      },
      {
        "from": 70,
        "to": 68
      },
      {
        "from": 62,
        "to": 60
      },
      {
        "from": 69,
        "to": 80
      },
      {
        "from": 9,
        "to": 12
      },
      {
        "from": 45,
        "to": 27
      },
      {
        "from": 60,
        "to": 51
      },
      {
        "from": 27,
        "to": 29
      },
      {
        "from": 20,
        "to": 1
      },
      {
        "from": 29,
        "to": 2
      },
      {
        "from": 1,
        "to": 18
      },
      {
        "from": 56,
        "to": 57
      },
      {
        "from": 7,
        "to": 24
      },
      {
        "from": 2,
        "to": 29
      },
      {
        "from": 31,
        "to": 40
      },
      {
        "from": 85,
        "to": 76
      },
      {
        "from": 12,
        "to": 17
      },
      {
        "from": 87,
        "to": 62
      },
      {
        "from": 17,
        "to": 62
      },
      {
        "from": 76,
        "to": 67
      },
      {
        "from": 62,
        "to": 17
      },
      {
        "from": 29,
        "to": 11
      },
      {
        "from": 17,
        "to": 11
      },
      {
        "from": 68,
        "to": 66
      },
      {
        "from": 11,
        "to": 83
      },
      {
        "from": 82,
        "to": 63
      },
      {
        "from": 83,
        "to": 84
      },
      {
        "from": 66,
        "to": 21
      },
      {
        "from": 84,
        "to": 83
      },
      {
        "from": 21,
        "to": 84
      },
      {
        "from": 83,
        "to": 84
      },
      {
        "from": 58,
        "to": 49
      }
    ],
    "tier": 2,
    "source": "generated"
  }
];
