// Generated by scripts/gen-routes.mjs — edit the generator, not this file.
import { ContactPage, contactMetadata } from '@/components/pages';

export const metadata = contactMetadata('zh');

export default function Page() {
  return <ContactPage locale="zh" />;
}

